name: Deploy Discord Bot

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This step ensures your code is checked out

      - name: Install FFmpeg and ALSA
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg alsa-utils

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install discord-py-interactions
          pip install pynacl
          pip install discord.py
          pip install -r requirements.txt  # Install packages from requirements.txt

      - name: Set up Pygame
        run: |
          pip install pygame

      - name: Run the bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # Use the secret stored in GitHub
        run: python main.py  # Start your Discord bot
